class_name WildTerrainProfile
extends RefCounted

const DEFAULT_PROFILE_ID := "plain"


static func supported_profile_ids() -> Array[String]:
	return ["plain", "forest_edge", "riverbank", "foothill"]


static func get_profile(profile_id: String) -> Dictionary:
	var profiles := _profiles()
	if not profiles.has(profile_id):
		return {}

	var profile: Dictionary = (profiles.get(profile_id, {}) as Dictionary).duplicate(true)
	profile["id"] = profile_id
	return profile


static func _profiles() -> Dictionary:
	return {
		"plain": {
			"display_name": "Plain",
			"base_height": 0.51,
			"height_amplitude": 0.34,
			"height_scale": 21.0,
			"moisture_bias": 0.47,
			"moisture_amplitude": 0.38,
			"moisture_scale": 15.0,
			"roughness_bias": 0.34,
			"roughness_amplitude": 0.30,
			"roughness_scale": 10.0,
			"vegetation_bias": 0.40,
			"vegetation_amplitude": 0.40,
			"vegetation_scale": 13.0,
			"rock_bias": 0.20,
			"rock_amplitude": 0.32,
			"rock_scale": 11.0,
			"water_level": 0.51,
			"water_softness": 0.28,
			"river_influence": 0.10,
			"pond_influence": 0.58,
			"pond_scale": 18.0,
			"pond_threshold": 0.56,
			"drainage_influence": 0.26,
			"deep_water_threshold": 0.78,
			"shallow_water_threshold": 0.20,
			"marsh_water_threshold": 0.26,
			"wet_meadow_water_threshold": 0.15,
			"mud_moisture_threshold": 0.54,
			"lowland_height_threshold": 0.48,
			"highland_height_threshold": 0.56,
			"ridge_height_threshold": 0.59,
			"slope_threshold": 0.014,
			"steep_slope_threshold": 0.045,
			"ridge_prominence_threshold": 0.012,
			"ledge_block_chance": 0.035,
			"woodland_mass_threshold": 0.55,
			"open_ground_threshold": 0.35,
			"forest_threshold": 0.70,
			"rocky_threshold": 0.68,
			"stone_threshold": 0.57,
			"tree_density": 0.125,
			"rock_density": 0.070,
			"herb_density": 0.018,
			"berry_density": 0.009,
			"ore_density": 0.006,
			"fallen_branch_density": 0.014,
		},
		"forest_edge": {
			"display_name": "Forest Edge",
			"base_height": 0.50,
			"height_amplitude": 0.32,
			"height_scale": 18.0,
			"moisture_bias": 0.56,
			"moisture_amplitude": 0.40,
			"moisture_scale": 13.0,
			"roughness_bias": 0.36,
			"roughness_amplitude": 0.34,
			"roughness_scale": 9.0,
			"vegetation_bias": 0.62,
			"vegetation_amplitude": 0.46,
			"vegetation_scale": 12.0,
			"rock_bias": 0.18,
			"rock_amplitude": 0.30,
			"rock_scale": 10.0,
			"water_level": 0.43,
			"water_softness": 0.21,
			"river_influence": 0.14,
			"pond_influence": 0.28,
			"pond_scale": 16.0,
			"pond_threshold": 0.66,
			"drainage_influence": 0.22,
			"deep_water_threshold": 0.72,
			"shallow_water_threshold": 0.36,
			"marsh_water_threshold": 0.30,
			"wet_meadow_water_threshold": 0.18,
			"mud_moisture_threshold": 0.58,
			"lowland_height_threshold": 0.46,
			"highland_height_threshold": 0.57,
			"ridge_height_threshold": 0.60,
			"slope_threshold": 0.016,
			"steep_slope_threshold": 0.048,
			"ridge_prominence_threshold": 0.014,
			"ledge_block_chance": 0.045,
			"woodland_mass_threshold": 0.44,
			"open_ground_threshold": 0.30,
			"forest_threshold": 0.62,
			"rocky_threshold": 0.70,
			"stone_threshold": 0.60,
			"tree_density": 0.185,
			"rock_density": 0.035,
			"herb_density": 0.024,
			"berry_density": 0.024,
			"ore_density": 0.002,
			"fallen_branch_density": 0.030,
		},
		"riverbank": {
			"display_name": "Riverbank",
			"base_height": 0.48,
			"height_amplitude": 0.36,
			"height_scale": 22.0,
			"moisture_bias": 0.64,
			"moisture_amplitude": 0.42,
			"moisture_scale": 14.0,
			"roughness_bias": 0.34,
			"roughness_amplitude": 0.30,
			"roughness_scale": 10.0,
			"vegetation_bias": 0.52,
			"vegetation_amplitude": 0.42,
			"vegetation_scale": 12.0,
			"rock_bias": 0.16,
			"rock_amplitude": 0.28,
			"rock_scale": 10.0,
			"water_level": 0.49,
			"water_softness": 0.24,
			"river_influence": 0.94,
			"pond_influence": 0.36,
			"pond_scale": 20.0,
			"pond_threshold": 0.60,
			"drainage_influence": 0.38,
			"deep_water_threshold": 0.66,
			"shallow_water_threshold": 0.30,
			"marsh_water_threshold": 0.26,
			"wet_meadow_water_threshold": 0.16,
			"mud_moisture_threshold": 0.50,
			"lowland_height_threshold": 0.48,
			"highland_height_threshold": 0.57,
			"ridge_height_threshold": 0.60,
			"slope_threshold": 0.015,
			"steep_slope_threshold": 0.046,
			"ridge_prominence_threshold": 0.012,
			"ledge_block_chance": 0.040,
			"woodland_mass_threshold": 0.52,
			"open_ground_threshold": 0.34,
			"forest_threshold": 0.70,
			"rocky_threshold": 0.72,
			"stone_threshold": 0.62,
			"tree_density": 0.080,
			"rock_density": 0.026,
			"herb_density": 0.032,
			"berry_density": 0.016,
			"ore_density": 0.002,
			"fallen_branch_density": 0.018,
		},
		"foothill": {
			"display_name": "Foothill",
			"base_height": 0.58,
			"height_amplitude": 0.46,
			"height_scale": 17.0,
			"moisture_bias": 0.42,
			"moisture_amplitude": 0.34,
			"moisture_scale": 13.0,
			"roughness_bias": 0.55,
			"roughness_amplitude": 0.42,
			"roughness_scale": 8.0,
			"vegetation_bias": 0.40,
			"vegetation_amplitude": 0.38,
			"vegetation_scale": 11.0,
			"rock_bias": 0.48,
			"rock_amplitude": 0.42,
			"rock_scale": 8.0,
			"water_level": 0.36,
			"water_softness": 0.15,
			"river_influence": 0.06,
			"pond_influence": 0.12,
			"pond_scale": 14.0,
			"pond_threshold": 0.72,
			"drainage_influence": 0.10,
			"deep_water_threshold": 0.73,
			"shallow_water_threshold": 0.38,
			"marsh_water_threshold": 0.34,
			"wet_meadow_water_threshold": 0.22,
			"mud_moisture_threshold": 0.62,
			"lowland_height_threshold": 0.48,
			"highland_height_threshold": 0.56,
			"ridge_height_threshold": 0.61,
			"slope_threshold": 0.018,
			"steep_slope_threshold": 0.052,
			"ridge_prominence_threshold": 0.014,
			"ledge_block_chance": 0.120,
			"woodland_mass_threshold": 0.58,
			"open_ground_threshold": 0.36,
			"forest_threshold": 0.68,
			"rocky_threshold": 0.60,
			"stone_threshold": 0.50,
			"tree_density": 0.075,
			"rock_density": 0.140,
			"herb_density": 0.012,
			"berry_density": 0.008,
			"ore_density": 0.012,
			"fallen_branch_density": 0.012,
		},
	}
